version: 1

merge:
  trigger:
    comment_substrings: ["==MERGE_WHEN_READY=="]
  ignore:
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: squash
  options:
    squash:
      title: "==MERGE_WHEN_READY=="
  delete_after_merge: true
  allow_merge_with_no_checks: true

update:
  trigger:
    labels: ["wip", "update me"]
