policy:
  approval:
    - the devtools team has approved
approval_rules:
  - name: the devtools team has approved
    has_author_in:
      users:
        - tc18
    requires:
      count: 1
      users:
        - RAVITEJA94
